services:
  postgres:
    image: postgres:16-alpine
    container_name: neobank-db
    environment:
      POSTGRES_DB: neobank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - neobank_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neobank"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neobank_data:
